CREATE DATABASE IF NOT EXISTS futour_sight;
 
USE futour_sight;
 
 
CREATE TABLE nivel_permissao (
    id_nivel_permissao INT AUTO_INCREMENT PRIMARY KEY,
    nome               VARCHAR(50)  NOT NULL UNIQUE,
    descricao          VARCHAR(255)
);
 
INSERT INTO nivel_permissao (nome, descricao) VALUES
('PLATAFORMA_ADMIN', 'Administrador da FuTour Sight - acesso total ao sistema'),
('EMPRESA_ADMIN',    'Administrador da empresa cliente - gerencia sua equipe'),
('EMPRESA_USER',     'Funcionario da empresa - acesso ao dashboard');
 
 
CREATE TABLE status (
    id_status INT AUTO_INCREMENT PRIMARY KEY,
    contexto  VARCHAR(50) NOT NULL,
    nome      VARCHAR(50) NOT NULL,
    descricao VARCHAR(255)
);
 
INSERT INTO status (contexto, nome, descricao) VALUES
('EMPRESA',     'ATIVA',      'Empresa ativa na plataforma'),
('EMPRESA',     'SUSPENSA',   'Empresa temporariamente suspensa'),
('EMPRESA',     'PENDENTE',   'Aguardando ativacao'),
('USUARIO',     'ATIVO',      'Usuario com acesso liberado'),
('USUARIO',     'INATIVO',    'Usuario desativado'),
('USUARIO',     'PENDENTE',   'Aguardando primeiro acesso'),
('UNIDADE',     'ATIVA',      'Unidade em operacao'),
('UNIDADE',     'INATIVA',    'Unidade desativada'),
('SOLICITACAO', 'PENDENTE',   'Aguardando analise do administrador'),
('SOLICITACAO', 'EM_ANALISE', 'Em analise pelo administrador'),
('SOLICITACAO', 'APROVADA',   'Solicitacao aprovada e processada'),
('SOLICITACAO', 'RECUSADA',   'Solicitacao recusada pelo administrador');
 
 
CREATE TABLE contato (
    id_contato   INT AUTO_INCREMENT PRIMARY KEY,
    nome         VARCHAR(150) NOT NULL,
    email        VARCHAR(150) NOT NULL,
    telefone     VARCHAR(20),
    mensagem     TEXT         NOT NULL,
    data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP
);
 
 
CREATE TABLE empresa (
    id_empresa       INT AUTO_INCREMENT PRIMARY KEY,
    nome             VARCHAR(150) NOT NULL,
    cnpj             CHAR(14)     NOT NULL UNIQUE,
    email            VARCHAR(150) UNIQUE,
    telefone         VARCHAR(20),
    fk_status        INT          NOT NULL DEFAULT 3,
    data_criacao     DATETIME DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (fk_status) REFERENCES status(id_status)
);
 
INSERT INTO empresa (nome, cnpj, email, telefone, fk_status) VALUES
('FutourSight', '01253456200015', 'futoursight@gmail.com', '11944444444', 1),
('Hotel Haddock', '53145733000180', 'hotelhaddock@gmail.com', '1127888634', 1);
 
 
CREATE TABLE usuario (
    id_usuario         INT AUTO_INCREMENT PRIMARY KEY,
    nome               VARCHAR(150),
    email              VARCHAR(150) NOT NULL UNIQUE,
    senha              VARCHAR(255),
    fk_nivel_permissao INT          NOT NULL,
    fk_empresa         INT,
    fk_status          INT          NOT NULL DEFAULT 6,
    primeiro_acesso    BOOLEAN DEFAULT TRUE,
    data_criacao       DATETIME DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao   DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (fk_nivel_permissao) REFERENCES nivel_permissao(id_nivel_permissao),
    FOREIGN KEY (fk_empresa)         REFERENCES empresa(id_empresa),
    FOREIGN KEY (fk_status)          REFERENCES status(id_status)
);
 
INSERT INTO usuario (nome, email, senha, fk_nivel_permissao, fk_empresa, fk_status) VALUES
('Reginaldo de Souza',  'reginaldo@futoursight.com.br',        'Senha@1234', 1, 1, 4),
('Debora Marsal',       'deboramarsal@futoursight.com.br',     'Senha@4321', 1, 1, 4),
('Lucas Eiki Gushiken', 'lucaseiki@futoursight.com.br',        'Senha@1232', 1, 1, 4),
('Gabriel Rodrigues',   'gabrielrodrigues@futoursight.com.br', 'Senha@1333', 1, 1, 4),
('Lucas Frossi',        'lucasfrossi@futoursight.com.br',      'Senha@4123', 1, 1, 4),
('Jorge Araújo',        'jorgearaujo@haddock.com.br',      'Codig0@123', 2, 2, 4),
('Mariana Martins',        'marianamartins@haddock.com.br',      'Codig0@224', 3, 2, 4);
 
CREATE TABLE solicitacao_cadastro (
    id_solicitacao       INT AUTO_INCREMENT PRIMARY KEY,
    nome_responsavel     VARCHAR(150) NOT NULL,
    email_responsavel    VARCHAR(150) NOT NULL,
    telefone_responsavel VARCHAR(20),
    nome_empresa         VARCHAR(150) NOT NULL,
    cnpj_empresa         CHAR(14)     NOT NULL,
    email_empresa        VARCHAR(150),
    telefone_empresa     VARCHAR(20),
    fk_status            INT          NOT NULL DEFAULT 9,
    data_criacao         DATETIME DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao     DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (fk_status) REFERENCES status(id_status)
);
 
 
CREATE TABLE endereco (
    id_endereco  INT AUTO_INCREMENT PRIMARY KEY,
    cep          CHAR(8),
    logradouro   VARCHAR(100),
    numero       CHAR(6),
    bairro       VARCHAR(100),
    cidade       VARCHAR(100),
    estado       VARCHAR(100),
    complemento  VARCHAR(100),
    fk_status    INT NOT NULL DEFAULT 7,
    fk_empresa   INT NOT NULL,
    data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (fk_status)  REFERENCES status(id_status),
    FOREIGN KEY (fk_empresa) REFERENCES empresa(id_empresa)
);

INSERT INTO endereco (cep, logradouro, numero, bairro, cidade, estado, complemento, fk_status, fk_empresa) VALUES
('11706230', 'Rua São Cristóvão', '331', 'Caiçara', 'Praia Grande', 'São Paulo', null, 7, 2);
 
CREATE TABLE log (
    id_log          INT AUTO_INCREMENT PRIMARY KEY,
    tabela          VARCHAR(100) NOT NULL,
    registros_lidos INT DEFAULT 0,
    sucesso         BOOLEAN      NOT NULL,
    mensagem        TEXT,
    data_criacao    DATETIME DEFAULT CURRENT_TIMESTAMP
);
 
 
CREATE TABLE chegadas_turistas (
    id               INT AUTO_INCREMENT PRIMARY KEY,
    via_de_acesso    VARCHAR(20),
    uf               VARCHAR(50),
    nome_pais_origem VARCHAR(100),
    mes              VARCHAR(20),
    ano              INT,
    chegadas         INT
);

INSERT INTO chegadas_turistas (via_de_acesso, uf, nome_pais_origem, mes, ano, chegadas) VALUES
('Aérea', 'Outras Unidades da Federação', 'Alemanha', 'Janeiro', 2024, 10),
('Aérea', 'Outras Unidades da Federação', 'Argentina', 'Janeiro', 2024, 1197),
('Aérea', 'Outras Unidades da Federação', 'Bélgica', 'Janeiro', 2024, 3),
('Aérea', 'Outras Unidades da Federação', 'Canadá', 'Janeiro', 2024, 2),
('Aérea', 'Outras Unidades da Federação', 'Chile', 'Janeiro', 2024, 1),
('Aérea', 'Outras Unidades da Federação', 'Dinamarca', 'Janeiro', 2024, 2),
('Aérea', 'Outras Unidades da Federação', 'Eslováquia', 'Janeiro', 2024, 1),
('Aérea', 'Outras Unidades da Federação', 'Espanha', 'Janeiro', 2024, 9),
('Aérea', 'Outras Unidades da Federação', 'Estados Unidos', 'Janeiro', 2024, 1),
('Aérea', 'Outras Unidades da Federação', 'França', 'Janeiro', 2024, 8),
('Aérea', 'Outras Unidades da Federação', 'Holanda', 'Janeiro', 2024, 2),
('Aérea', 'Outras Unidades da Federação', 'Irlanda', 'Janeiro', 2024, 3),
('Aérea', 'Outras Unidades da Federação', 'Itália', 'Janeiro', 2024, 77),
('Aérea', 'Outras Unidades da Federação', 'Letônia', 'Janeiro', 2024, 1),
('Aérea', 'Outras Unidades da Federação', 'México', 'Janeiro', 2024, 1),
('Aérea', 'Outras Unidades da Federação', 'Paraguai', 'Janeiro', 2024, 1),
('Aérea', 'Outras Unidades da Federação', 'Polônia', 'Janeiro', 2024, 1),
('Aérea', 'Outras Unidades da Federação', 'Portugal', 'Janeiro', 2024, 270),
('Aérea', 'Outras Unidades da Federação', 'Reino Unido', 'Janeiro', 2024, 5),
('Aérea', 'Outras Unidades da Federação', 'Rússia', 'Janeiro', 2024, 5),
('Aérea', 'Outras Unidades da Federação', 'Suécia', 'Janeiro', 2024, 1),
('Aérea', 'Outras Unidades da Federação', 'Suíça', 'Janeiro', 2024, 13),
('Aérea', 'Outras Unidades da Federação', 'Ucrânia', 'Janeiro', 2024, 1),
('Aérea', 'Outras Unidades da Federação', 'Venezuela', 'Janeiro', 2024, 4),
('Aérea', 'Amapá', 'Itália', 'Janeiro', 2024, 2),
('Aérea', 'Amazonas', 'Alemanha', 'Janeiro', 2024, 27),
('Aérea', 'Amazonas', 'Angola', 'Janeiro', 2024, 1),
('Aérea', 'Amazonas', 'Argentina', 'Janeiro', 2024, 8),
('Aérea', 'Amazonas', 'Austrália', 'Janeiro', 2024, 11),
('Aérea', 'Amazonas', 'Bélgica', 'Janeiro', 2024, 3),
('Aérea', 'Amazonas', 'Outros países da América Central e Caribe', 'Janeiro', 2024, 1),
('Aérea', 'Amazonas', 'Canadá', 'Janeiro', 2024, 94),
('Aérea', 'Amazonas', 'China', 'Janeiro', 2024, 8),
('Aérea', 'Amazonas', 'China, Hong Kong', 'Janeiro', 2024, 2),
('Aérea', 'Amazonas', 'Colômbia', 'Janeiro', 2024, 75),
('Aérea', 'Amazonas', 'Costa Rica', 'Janeiro', 2024, 8),
('Aérea', 'Amazonas', 'Dinamarca', 'Janeiro', 2024, 5),
('Aérea', 'Amazonas', 'El Salvador', 'Janeiro', 2024, 1),
('Aérea', 'Amazonas', 'Equador', 'Janeiro', 2024, 14),
('Aérea', 'Amazonas', 'Eslováquia', 'Janeiro', 2024, 1),
('Aérea', 'Amazonas', 'Espanha', 'Janeiro', 2024, 7),
('Aérea', 'Amazonas', 'Estados Unidos', 'Janeiro', 2024, 1118),
('Aérea', 'Amazonas', 'Filipinas', 'Janeiro', 2024, 1),
('Aérea', 'Amazonas', 'França', 'Janeiro', 2024, 25),
('Aérea', 'Amazonas', 'Grécia', 'Janeiro', 2024, 1),
('Aérea', 'Amazonas', 'Guatemala', 'Janeiro', 2024, 2),
('Aérea', 'Amazonas', 'Guiana', 'Janeiro', 2024, 6),
('Aérea', 'Amazonas', 'Holanda', 'Janeiro', 2024, 3),
('Aérea', 'Amazonas', 'Honduras', 'Janeiro', 2024, 2),
('Aérea', 'Amazonas', 'Hungria', 'Janeiro', 2024, 1),
('Aérea', 'Amazonas', 'Índia', 'Janeiro', 2024, 2),
('Aérea', 'Amazonas', 'Irlanda', 'Janeiro', 2024, 10),
('Aérea', 'Amazonas', 'Israel', 'Janeiro', 2024, 2),
('Aérea', 'Amazonas', 'Itália', 'Janeiro', 2024, 8),
('Aérea', 'Amazonas', 'Japão', 'Janeiro', 2024, 17),
('Aérea', 'Amazonas', 'Letônia', 'Janeiro', 2024, 2),
('Aérea', 'Amazonas', 'Malásia', 'Janeiro', 2024, 2),
('Aérea', 'Amazonas', 'Outros países da Europa', 'Janeiro', 2024, 1),
('Aérea', 'Amazonas', 'Marrocos', 'Janeiro', 2024, 1),
('Aérea', 'Amazonas', 'México', 'Janeiro', 2024, 36),
('Aérea', 'Amazonas', 'Moçambique', 'Janeiro', 2024, 1),
('Aérea', 'Amazonas', 'Outros países da Europa', 'Janeiro', 2024, 1),
('Aérea', 'Amazonas', 'Noruega', 'Janeiro', 2024, 2),
('Aérea', 'Amazonas', 'Panamá', 'Janeiro', 2024, 7),
('Aérea', 'Amazonas', 'Paquistão', 'Janeiro', 2024, 1),
('Aérea', 'Amazonas', 'Peru', 'Janeiro', 2024, 20),
('Aérea', 'Amazonas', 'Polônia', 'Janeiro', 2024, 15),
('Aérea', 'Amazonas', 'Portugal', 'Janeiro', 2024, 7),
('Aérea', 'Amazonas', 'Reino Unido', 'Janeiro', 2024, 32),
('Aérea', 'Amazonas', 'República da Coreia', 'Janeiro', 2024, 5),
('Aérea', 'Amazonas', 'República Dominicana', 'Janeiro', 2024, 3),
('Aérea', 'Amazonas', 'República Tcheca', 'Janeiro', 2024, 1),
('Aérea', 'Amazonas', 'Romênia', 'Janeiro', 2024, 1),
('Aérea', 'Amazonas', 'Rússia', 'Janeiro', 2024, 7),
('Aérea', 'Amazonas', 'Suécia', 'Janeiro', 2024, 2),
('Aérea', 'Amazonas', 'Suíça', 'Janeiro', 2024, 10),
('Aérea', 'Amazonas', 'Suriname', 'Janeiro', 2024, 4),
('Aérea', 'Amazonas', 'Tailândia', 'Janeiro', 2024, 1),
('Aérea', 'Amazonas', 'Venezuela', 'Janeiro', 2024, 22),
('Aérea', 'Bahia', 'Argentina', 'Janeiro', 2024, 1272),
('Aérea', 'Bahia', 'Bolívia', 'Janeiro', 2024, 1),
('Aérea', 'Bahia', 'Chile', 'Janeiro', 2024, 1),
('Aérea', 'Bahia', 'Colômbia', 'Janeiro', 2024, 1),
('Aérea', 'Bahia', 'Equador', 'Janeiro', 2024, 1),
('Aérea', 'Bahia', 'Espanha', 'Janeiro', 2024, 4),
('Aérea', 'Bahia', 'Estados Unidos', 'Janeiro', 2024, 6),
('Aérea', 'Bahia', 'França', 'Janeiro', 2024, 3),
('Aérea', 'Bahia', 'Outros países da Europa', 'Janeiro', 2024, 1),
('Aérea', 'Bahia', 'Grécia', 'Janeiro', 2024, 1),
('Aérea', 'Bahia', 'Itália', 'Janeiro', 2024, 1),
('Aérea', 'Bahia', 'Peru', 'Janeiro', 2024, 3),
('Aérea', 'Bahia', 'Polônia', 'Janeiro', 2024, 2),
('Aérea', 'Bahia', 'Portugal', 'Janeiro', 2024, 2),
('Aérea', 'Bahia', 'Suíça', 'Janeiro', 2024, 1),
('Aérea', 'Bahia', 'Uruguai', 'Janeiro', 2024, 1),
('Aérea', 'Bahia', 'Alemanha', 'Janeiro', 2024, 596),
('Aérea', 'Bahia', 'Outros países da Europa', 'Janeiro', 2024, 1),
('Aérea', 'Bahia', 'Angola', 'Janeiro', 2024, 2),
('Aérea', 'Bahia', 'Outros países da América Central e Caribe', 'Janeiro', 2024, 1),
('Aérea', 'Bahia', 'Argentina', 'Janeiro', 2024, 6484),
('Aérea', 'Bahia', 'Austrália', 'Janeiro', 2024, 2),
('Aérea', 'Bahia', 'Áustria', 'Janeiro', 2024, 33),
('Aérea', 'Bahia', 'Bélgica', 'Janeiro', 2024, 74),
('Aérea', 'Bahia', 'Outros países da Europa', 'Janeiro', 2024, 5),
('Aérea', 'Bahia', 'Bolívia', 'Janeiro', 2024, 3),
('Aérea', 'Bahia', 'Bulgária', 'Janeiro', 2024, 3),
('Aérea', 'Bahia', 'Cabo Verde', 'Janeiro', 2024, 1),
('Aérea', 'Bahia', 'Canadá', 'Janeiro', 2024, 5),
('Aérea', 'Bahia', 'Chile', 'Janeiro', 2024, 553),
('Aérea', 'Bahia', 'Outros países da Ásia', 'Janeiro', 2024, 1),
('Aérea', 'Bahia', 'Colômbia', 'Janeiro', 2024, 11),
('Aérea', 'Bahia', 'Croácia', 'Janeiro', 2024, 7),
('Aérea', 'Bahia', 'Dinamarca', 'Janeiro', 2024, 17),
('Aérea', 'Bahia', 'El Salvador', 'Janeiro', 2024, 1),
('Aérea', 'Bahia', 'Eslováquia', 'Janeiro', 2024, 3),
('Aérea', 'Bahia', 'Eslovênia', 'Janeiro', 2024, 2),
('Aérea', 'Bahia', 'Espanha', 'Janeiro', 2024, 368),
('Aérea', 'Bahia', 'Estados Unidos', 'Janeiro', 2024, 86),
('Aérea', 'Bahia', 'Estônia', 'Janeiro', 2024, 2),
('Aérea', 'Bahia', 'Filipinas', 'Janeiro', 2024, 2),
('Aérea', 'Bahia', 'França', 'Janeiro', 2024, 602),
('Aérea', 'Bahia', 'Grécia', 'Janeiro', 2024, 11),
('Aérea', 'Bahia', 'Outros países da África', 'Janeiro', 2024, 2),
('Aérea', 'Bahia', 'Holanda', 'Janeiro', 2024, 339),
('Aérea', 'Bahia', 'Hungria', 'Janeiro', 2024, 3),
('Aérea', 'Bahia', 'Índia', 'Janeiro', 2024, 2),
('Aérea', 'Bahia', 'Irlanda', 'Janeiro', 2024, 28),
('Aérea', 'Bahia', 'Outros países da Europa', 'Janeiro', 2024, 1),
('Aérea', 'Bahia', 'Israel', 'Janeiro', 2024, 29),
('Aérea', 'Bahia', 'Itália', 'Janeiro', 2024, 1080),
('Aérea', 'Bahia', 'Lituânia', 'Janeiro', 2024, 23),
('Aérea', 'Bahia', 'Luxemburgo', 'Janeiro', 2024, 3),
('Aérea', 'Bahia', 'Outros países da Europa', 'Janeiro', 2024, 1),
('Aérea', 'Bahia', 'Marrocos', 'Janeiro', 2024, 1),
('Aérea', 'Bahia', 'México', 'Janeiro', 2024, 5),
('Aérea', 'Bahia', 'Moçambique', 'Janeiro', 2024, 1),
('Aérea', 'Bahia', 'Noruega', 'Janeiro', 2024, 15),
('Aérea', 'Bahia', 'Paraguai', 'Janeiro', 2024, 13),
('Aérea', 'Bahia', 'Peru', 'Janeiro', 2024, 6),
('Aérea', 'Bahia', 'Polônia', 'Janeiro', 2024, 1386),
('Aérea', 'Bahia', 'Portugal', 'Janeiro', 2024, 1358),
('Aérea', 'Bahia', 'Reino Unido', 'Janeiro', 2024, 163),
('Aérea', 'Bahia', 'República da Coreia', 'Janeiro', 2024, 10),
('Aérea', 'Bahia', 'República Dominicana', 'Janeiro', 2024, 3),
('Aérea', 'Bahia', 'República Tcheca', 'Janeiro', 2024, 2),
('Aérea', 'Bahia', 'Romênia', 'Janeiro', 2024, 10),
('Aérea', 'Bahia', 'Rússia', 'Janeiro', 2024, 8),
('Aérea', 'Bahia', 'Sérvia', 'Janeiro', 2024, 2),
('Aérea', 'Bahia', 'Suécia', 'Janeiro', 2024, 31),
('Aérea', 'Bahia', 'Suíça', 'Janeiro', 2024, 387),
('Aérea', 'Bahia', 'Turquia', 'Janeiro', 2024, 3),
('Aérea', 'Bahia', 'Ucrânia', 'Janeiro', 2024, 16),
('Aérea', 'Bahia', 'Uruguai', 'Janeiro', 2024, 1296),
('Aérea', 'Bahia', 'Venezuela', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Outros países da Europa', 'Janeiro', 2024, 2),
('Aérea', 'Ceará', 'Alemanha', 'Janeiro', 2024, 354),
('Aérea', 'Ceará', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Argentina', 'Janeiro', 2024, 760),
('Aérea', 'Ceará', 'Áustria', 'Janeiro', 2024, 49),
('Aérea', 'Ceará', 'Bélgica', 'Janeiro', 2024, 70),
('Aérea', 'Ceará', 'Outros países da Europa', 'Janeiro', 2024, 2),
('Aérea', 'Ceará', 'Outros países da Europa', 'Janeiro', 2024, 2),
('Aérea', 'Ceará', 'Bulgária', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Cabo Verde', 'Janeiro', 2024, 4),
('Aérea', 'Ceará', 'Canadá', 'Janeiro', 2024, 29),
('Aérea', 'Ceará', 'Outros países da Ásia', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Chile', 'Janeiro', 2024, 5),
('Aérea', 'Ceará', 'China', 'Janeiro', 2024, 3),
('Aérea', 'Ceará', 'China, Hong Kong', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Colômbia', 'Janeiro', 2024, 6),
('Aérea', 'Ceará', 'Croácia', 'Janeiro', 2024, 3),
('Aérea', 'Ceará', 'Dinamarca', 'Janeiro', 2024, 36),
('Aérea', 'Ceará', 'El Salvador', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Equador', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Eslováquia', 'Janeiro', 2024, 2),
('Aérea', 'Ceará', 'Eslovênia', 'Janeiro', 2024, 8),
('Aérea', 'Ceará', 'Espanha', 'Janeiro', 2024, 188),
('Aérea', 'Ceará', 'Estados Unidos', 'Janeiro', 2024, 329),
('Aérea', 'Ceará', 'Estônia', 'Janeiro', 2024, 2),
('Aérea', 'Ceará', 'Finlândia', 'Janeiro', 2024, 16),
('Aérea', 'Ceará', 'França', 'Janeiro', 2024, 715),
('Aérea', 'Ceará', 'Outros países da Europa', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Grécia', 'Janeiro', 2024, 10),
('Aérea', 'Ceará', 'Outros países da África', 'Janeiro', 2024, 2),
('Aérea', 'Ceará', 'Holanda', 'Janeiro', 2024, 259),
('Aérea', 'Ceará', 'Honduras', 'Janeiro', 2024, 4),
('Aérea', 'Ceará', 'Hungria', 'Janeiro', 2024, 16),
('Aérea', 'Ceará', 'Índia', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Indonésia', 'Janeiro', 2024, 4),
('Aérea', 'Ceará', 'Irã', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Irlanda', 'Janeiro', 2024, 16),
('Aérea', 'Ceará', 'Israel', 'Janeiro', 2024, 6),
('Aérea', 'Ceará', 'Itália', 'Janeiro', 2024, 938),
('Aérea', 'Ceará', 'Japão', 'Janeiro', 2024, 6),
('Aérea', 'Ceará', 'Letônia', 'Janeiro', 2024, 6),
('Aérea', 'Ceará', 'Outros países da Europa', 'Janeiro', 2024, 3),
('Aérea', 'Ceará', 'Lituânia', 'Janeiro', 2024, 10),
('Aérea', 'Ceará', 'Luxemburgo', 'Janeiro', 2024, 2),
('Aérea', 'Ceará', 'Outros países da Europa', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Marrocos', 'Janeiro', 2024, 3),
('Aérea', 'Ceará', 'México', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Outros países da Europa', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Nicarágua', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Noruega', 'Janeiro', 2024, 118),
('Aérea', 'Ceará', 'Panamá', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Paraguai', 'Janeiro', 2024, 4),
('Aérea', 'Ceará', 'Peru', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Polônia', 'Janeiro', 2024, 89),
('Aérea', 'Ceará', 'Portugal', 'Janeiro', 2024, 1708),
('Aérea', 'Ceará', 'Quênia', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Reino Unido', 'Janeiro', 2024, 104),
('Aérea', 'Ceará', 'República da Coreia', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Outros países da Europa', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'República Dominicana', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'República Tcheca', 'Janeiro', 2024, 31),
('Aérea', 'Ceará', 'Romênia', 'Janeiro', 2024, 9),
('Aérea', 'Ceará', 'Rússia', 'Janeiro', 2024, 4),
('Aérea', 'Ceará', 'Sérvia', 'Janeiro', 2024, 3),
('Aérea', 'Ceará', 'Suécia', 'Janeiro', 2024, 40),
('Aérea', 'Ceará', 'Suíça', 'Janeiro', 2024, 191),
('Aérea', 'Ceará', 'Tunísia', 'Janeiro', 2024, 3),
('Aérea', 'Ceará', 'Turquia', 'Janeiro', 2024, 4),
('Aérea', 'Ceará', 'Ucrânia', 'Janeiro', 2024, 9),
('Aérea', 'Ceará', 'Uruguai', 'Janeiro', 2024, 1),
('Aérea', 'Ceará', 'Venezuela', 'Janeiro', 2024, 1),
('Aérea', 'Distrito Federal', 'Alemanha', 'Janeiro', 2024, 170),
('Aérea', 'Distrito Federal', 'Argentina', 'Janeiro', 2024, 2045),
('Aérea', 'Distrito Federal', 'Austrália', 'Janeiro', 2024, 11),
('Aérea', 'Distrito Federal', 'Áustria', 'Janeiro', 2024, 6),
('Aérea', 'Distrito Federal', 'Bélgica', 'Janeiro', 2024, 18),
('Aérea', 'Distrito Federal', 'Outros países da Europa', 'Janeiro', 2024, 1),
('Aérea', 'Distrito Federal', 'Bolívia', 'Janeiro', 2024, 4),
('Aérea', 'Distrito Federal', 'Bulgária', 'Janeiro', 2024, 3),
('Aérea', 'Distrito Federal', 'Canadá', 'Janeiro', 2024, 29),
('Aérea', 'Distrito Federal', 'Chile', 'Janeiro', 2024, 7),
('Aérea', 'Distrito Federal', 'China', 'Janeiro', 2024, 28),
('Aérea', 'Distrito Federal', 'Cingapura', 'Janeiro', 2024, 1),
('Aérea', 'Distrito Federal', 'Colômbia', 'Janeiro', 2024, 219),
('Aérea', 'Distrito Federal', 'Costa Rica', 'Janeiro', 2024, 8),
('Aérea', 'Distrito Federal', 'Croácia', 'Janeiro', 2024, 2),
('Aérea', 'Distrito Federal', 'Cuba', 'Janeiro', 2024, 16),
('Aérea', 'Distrito Federal', 'Dinamarca', 'Janeiro', 2024, 1),
('Aérea', 'Distrito Federal', 'Egito', 'Janeiro', 2024, 2),
('Aérea', 'Distrito Federal', 'El Salvador', 'Janeiro', 2024, 7),
('Aérea', 'Distrito Federal', 'Equador', 'Janeiro', 2024, 128),
('Aérea', 'Distrito Federal', 'Espanha', 'Janeiro', 2024, 145),
('Aérea', 'Distrito Federal', 'Estados Unidos', 'Janeiro', 2024, 1428),
('Aérea', 'Distrito Federal', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Distrito Federal', 'Finlândia', 'Janeiro', 2024, 2),
('Aérea', 'Distrito Federal', 'França', 'Janeiro', 2024, 108),
('Aérea', 'Distrito Federal', 'Outros países da Europa', 'Janeiro', 2024, 1),
('Aérea', 'Distrito Federal', 'Grécia', 'Janeiro', 2024, 4),
('Aérea', 'Distrito Federal', 'Guatemala', 'Janeiro', 2024, 6),
('Aérea', 'Distrito Federal', 'Guiana', 'Janeiro', 2024, 5),
('Aérea', 'Distrito Federal', 'Outros países da África', 'Janeiro', 2024, 5),
('Aérea', 'Distrito Federal', 'Haiti', 'Janeiro', 2024, 3),
('Aérea', 'Distrito Federal', 'Holanda', 'Janeiro', 2024, 21),
('Aérea', 'Distrito Federal', 'Hungria', 'Janeiro', 2024, 4),
('Aérea', 'Distrito Federal', 'Índia', 'Janeiro', 2024, 6),
('Aérea', 'Distrito Federal', 'Indonésia', 'Janeiro', 2024, 2),
('Aérea', 'Distrito Federal', 'Irã', 'Janeiro', 2024, 1),
('Aérea', 'Distrito Federal', 'Irlanda', 'Janeiro', 2024, 21),
('Aérea', 'Distrito Federal', 'Israel', 'Janeiro', 2024, 9),
('Aérea', 'Distrito Federal', 'Itália', 'Janeiro', 2024, 67),
('Aérea', 'Distrito Federal', 'Japão', 'Janeiro', 2024, 4),
('Aérea', 'Distrito Federal', 'Lituânia', 'Janeiro', 2024, 4),
('Aérea', 'Distrito Federal', 'Luxemburgo', 'Janeiro', 2024, 1),
('Aérea', 'Distrito Federal', 'Malásia', 'Janeiro', 2024, 1),
('Aérea', 'Distrito Federal', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Distrito Federal', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Distrito Federal', 'Marrocos', 'Janeiro', 2024, 2),
('Aérea', 'Distrito Federal', 'México', 'Janeiro', 2024, 27),
('Aérea', 'Distrito Federal', 'Moçambique', 'Janeiro', 2024, 3),
('Aérea', 'Distrito Federal', 'Nicarágua', 'Janeiro', 2024, 3),
('Aérea', 'Distrito Federal', 'Noruega', 'Janeiro', 2024, 15),
('Aérea', 'Distrito Federal', 'Nova Zelândia', 'Janeiro', 2024, 4),
('Aérea', 'Distrito Federal', 'Panamá', 'Janeiro', 2024, 17),
('Aérea', 'Distrito Federal', 'Paraguai', 'Janeiro', 2024, 7),
('Aérea', 'Distrito Federal', 'Peru', 'Janeiro', 2024, 371),
('Aérea', 'Distrito Federal', 'Polônia', 'Janeiro', 2024, 6),
('Aérea', 'Distrito Federal', 'Portugal', 'Janeiro', 2024, 825),
('Aérea', 'Distrito Federal', 'Reino Unido', 'Janeiro', 2024, 46),
('Aérea', 'Distrito Federal', 'República da Coreia', 'Janeiro', 2024, 3),
('Aérea', 'Distrito Federal', 'República Dominicana', 'Janeiro', 2024, 5),
('Aérea', 'Distrito Federal', 'República Tcheca', 'Janeiro', 2024, 21),
('Aérea', 'Distrito Federal', 'Romênia', 'Janeiro', 2024, 2),
('Aérea', 'Distrito Federal', 'Rússia', 'Janeiro', 2024, 5),
('Aérea', 'Distrito Federal', 'Outros países da América Central e Caribe', 'Janeiro', 2024, 1),
('Aérea', 'Distrito Federal', 'Outros países da África', 'Janeiro', 2024, 3),
('Aérea', 'Distrito Federal', 'Suécia', 'Janeiro', 2024, 7),
('Aérea', 'Distrito Federal', 'Suíça', 'Janeiro', 2024, 80),
('Aérea', 'Distrito Federal', 'Tailândia', 'Janeiro', 2024, 1),
('Aérea', 'Distrito Federal', 'Taiwan', 'Janeiro', 2024, 1),
('Aérea', 'Distrito Federal', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Distrito Federal', 'Trinidad e Tobago', 'Janeiro', 2024, 2),
('Aérea', 'Distrito Federal', 'Turquia', 'Janeiro', 2024, 6),
('Aérea', 'Distrito Federal', 'Ucrânia', 'Janeiro', 2024, 2),
('Aérea', 'Distrito Federal', 'Uruguai', 'Janeiro', 2024, 6),
('Aérea', 'Distrito Federal', 'Venezuela', 'Janeiro', 2024, 50),
('Aérea', 'Mato Grosso do Sul', 'Paraguai', 'Janeiro', 2024, 4),
('Aérea', 'Minas Gerais', 'África do Sul', 'Janeiro', 2024, 1),
('Aérea', 'Minas Gerais', 'Alemanha', 'Janeiro', 2024, 378),
('Aérea', 'Minas Gerais', 'Argentina', 'Janeiro', 2024, 70),
('Aérea', 'Minas Gerais', 'Austrália', 'Janeiro', 2024, 4),
('Aérea', 'Minas Gerais', 'Áustria', 'Janeiro', 2024, 5),
('Aérea', 'Minas Gerais', 'Bélgica', 'Janeiro', 2024, 36),
('Aérea', 'Minas Gerais', 'Bolívia', 'Janeiro', 2024, 1),
('Aérea', 'Minas Gerais', 'Canadá', 'Janeiro', 2024, 19),
('Aérea', 'Minas Gerais', 'Chile', 'Janeiro', 2024, 165),
('Aérea', 'Minas Gerais', 'China', 'Janeiro', 2024, 3),
('Aérea', 'Minas Gerais', 'Colômbia', 'Janeiro', 2024, 284),
('Aérea', 'Minas Gerais', 'Costa Rica', 'Janeiro', 2024, 28),
('Aérea', 'Minas Gerais', 'Croácia', 'Janeiro', 2024, 1),
('Aérea', 'Minas Gerais', 'Cuba', 'Janeiro', 2024, 3),
('Aérea', 'Minas Gerais', 'Outros países da América Central e Caribe', 'Janeiro', 2024, 1),
('Aérea', 'Minas Gerais', 'Dinamarca', 'Janeiro', 2024, 2),
('Aérea', 'Minas Gerais', 'El Salvador', 'Janeiro', 2024, 2),
('Aérea', 'Minas Gerais', 'Equador', 'Janeiro', 2024, 34),
('Aérea', 'Minas Gerais', 'Espanha', 'Janeiro', 2024, 41),
('Aérea', 'Minas Gerais', 'Estados Unidos', 'Janeiro', 2024, 442),
('Aérea', 'Minas Gerais', 'Estônia', 'Janeiro', 2024, 2),
('Aérea', 'Minas Gerais', 'Filipinas', 'Janeiro', 2024, 2),
('Aérea', 'Minas Gerais', 'Finlândia', 'Janeiro', 2024, 4),
('Aérea', 'Minas Gerais', 'França', 'Janeiro', 2024, 61),
('Aérea', 'Minas Gerais', 'Grécia', 'Janeiro', 2024, 2),
('Aérea', 'Minas Gerais', 'Guatemala', 'Janeiro', 2024, 4),
('Aérea', 'Minas Gerais', 'Haiti', 'Janeiro', 2024, 1),
('Aérea', 'Minas Gerais', 'Holanda', 'Janeiro', 2024, 22),
('Aérea', 'Minas Gerais', 'Honduras', 'Janeiro', 2024, 3),
('Aérea', 'Minas Gerais', 'Hungria', 'Janeiro', 2024, 2),
('Aérea', 'Minas Gerais', 'Irã', 'Janeiro', 2024, 1),
('Aérea', 'Minas Gerais', 'Irlanda', 'Janeiro', 2024, 26),
('Aérea', 'Minas Gerais', 'Israel', 'Janeiro', 2024, 4),
('Aérea', 'Minas Gerais', 'Itália', 'Janeiro', 2024, 194),
('Aérea', 'Minas Gerais', 'Outros países da Ásia', 'Janeiro', 2024, 1),
('Aérea', 'Minas Gerais', 'Marrocos', 'Janeiro', 2024, 1),
('Aérea', 'Minas Gerais', 'México', 'Janeiro', 2024, 26),
('Aérea', 'Minas Gerais', 'Noruega', 'Janeiro', 2024, 8),
('Aérea', 'Minas Gerais', 'Nova Zelândia', 'Janeiro', 2024, 5),
('Aérea', 'Minas Gerais', 'Panamá', 'Janeiro', 2024, 33),
('Aérea', 'Minas Gerais', 'Paraguai', 'Janeiro', 2024, 1),
('Aérea', 'Minas Gerais', 'Peru', 'Janeiro', 2024, 7),
('Aérea', 'Minas Gerais', 'Polônia', 'Janeiro', 2024, 6),
('Aérea', 'Minas Gerais', 'Portugal', 'Janeiro', 2024, 1374),
('Aérea', 'Minas Gerais', 'Reino Unido', 'Janeiro', 2024, 156),
('Aérea', 'Minas Gerais', 'República da Coreia', 'Janeiro', 2024, 2),
('Aérea', 'Minas Gerais', 'República Dominicana', 'Janeiro', 2024, 5),
('Aérea', 'Minas Gerais', 'República Tcheca', 'Janeiro', 2024, 1),
('Aérea', 'Minas Gerais', 'Romênia', 'Janeiro', 2024, 1),
('Aérea', 'Minas Gerais', 'Rússia', 'Janeiro', 2024, 2),
('Aérea', 'Minas Gerais', 'Outros países da América Central e Caribe', 'Janeiro', 2024, 1),
('Aérea', 'Minas Gerais', 'Suécia', 'Janeiro', 2024, 2),
('Aérea', 'Minas Gerais', 'Suíça', 'Janeiro', 2024, 34),
('Aérea', 'Minas Gerais', 'Ucrânia', 'Janeiro', 2024, 1),
('Aérea', 'Minas Gerais', 'Venezuela', 'Janeiro', 2024, 2),
('Aérea', 'Pará', 'África do Sul', 'Janeiro', 2024, 2),
('Aérea', 'Pará', 'Alemanha', 'Janeiro', 2024, 51),
('Aérea', 'Pará', 'Arábia Saudita', 'Janeiro', 2024, 2),
('Aérea', 'Pará', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Pará', 'Argentina', 'Janeiro', 2024, 2),
('Aérea', 'Pará', 'Áustria', 'Janeiro', 2024, 1),
('Aérea', 'Pará', 'Bélgica', 'Janeiro', 2024, 5),
('Aérea', 'Pará', 'Bolívia', 'Janeiro', 2024, 3),
('Aérea', 'Pará', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Pará', 'Canadá', 'Janeiro', 2024, 12),
('Aérea', 'Pará', 'Chile', 'Janeiro', 2024, 1),
('Aérea', 'Pará', 'China', 'Janeiro', 2024, 11),
('Aérea', 'Pará', 'Outros países da Ásia', 'Janeiro', 2024, 1),
('Aérea', 'Pará', 'Cingapura', 'Janeiro', 2024, 1),
('Aérea', 'Pará', 'Colômbia', 'Janeiro', 2024, 3),
('Aérea', 'Pará', 'Croácia', 'Janeiro', 2024, 1),
('Aérea', 'Pará', 'Dinamarca', 'Janeiro', 2024, 7),
('Aérea', 'Pará', 'Espanha', 'Janeiro', 2024, 26),
('Aérea', 'Pará', 'Estados Unidos', 'Janeiro', 2024, 229),
('Aérea', 'Pará', 'Estônia', 'Janeiro', 2024, 1),
('Aérea', 'Pará', 'Finlândia', 'Janeiro', 2024, 1),
('Aérea', 'Pará', 'França', 'Janeiro', 2024, 473),
('Aérea', 'Pará', 'Guiana', 'Janeiro', 2024, 4),
('Aérea', 'Pará', 'Holanda', 'Janeiro', 2024, 96),
('Aérea', 'Pará', 'Honduras', 'Janeiro', 2024, 1),
('Aérea', 'Pará', 'Irlanda', 'Janeiro', 2024, 2),
('Aérea', 'Pará', 'Israel', 'Janeiro', 2024, 3),
('Aérea', 'Pará', 'Itália', 'Janeiro', 2024, 14),
('Aérea', 'Pará', 'Outros países da América Central e Caribe', 'Janeiro', 2024, 1),
('Aérea', 'Pará', 'Outros países da Europa', 'Janeiro', 2024, 2),
('Aérea', 'Pará', 'Marrocos', 'Janeiro', 2024, 1),
('Aérea', 'Pará', 'México', 'Janeiro', 2024, 3),
('Aérea', 'Pará', 'Outros países da Ásia', 'Janeiro', 2024, 2),
('Aérea', 'Pará', 'Noruega', 'Janeiro', 2024, 20),
('Aérea', 'Pará', 'Peru', 'Janeiro', 2024, 6),
('Aérea', 'Pará', 'Polônia', 'Janeiro', 2024, 1),
('Aérea', 'Pará', 'Portugal', 'Janeiro', 2024, 209),
('Aérea', 'Pará', 'Reino Unido', 'Janeiro', 2024, 18),
('Aérea', 'Pará', 'República Dominicana', 'Janeiro', 2024, 4),
('Aérea', 'Pará', 'Romênia', 'Janeiro', 2024, 4),
('Aérea', 'Pará', 'Rússia', 'Janeiro', 2024, 3),
('Aérea', 'Pará', 'Suécia', 'Janeiro', 2024, 2),
('Aérea', 'Pará', 'Suíça', 'Janeiro', 2024, 13),
('Aérea', 'Pará', 'Suriname', 'Janeiro', 2024, 753),
('Aérea', 'Pará', 'Uruguai', 'Janeiro', 2024, 2),
('Aérea', 'Pará', 'Venezuela', 'Janeiro', 2024, 2),
('Aérea', 'Outras Unidades da Federação', 'Argentina', 'Janeiro', 2024, 16),
('Aérea', 'Paraná', 'Alemanha', 'Janeiro', 2024, 12),
('Aérea', 'Paraná', 'Argentina', 'Janeiro', 2024, 26),
('Aérea', 'Paraná', 'Austrália', 'Janeiro', 2024, 11),
('Aérea', 'Paraná', 'Áustria', 'Janeiro', 2024, 2),
('Aérea', 'Paraná', 'Canadá', 'Janeiro', 2024, 2),
('Aérea', 'Paraná', 'Chile', 'Janeiro', 2024, 1471),
('Aérea', 'Paraná', 'China', 'Janeiro', 2024, 11),
('Aérea', 'Paraná', 'Colômbia', 'Janeiro', 2024, 10),
('Aérea', 'Paraná', 'Costa Rica', 'Janeiro', 2024, 4),
('Aérea', 'Paraná', 'Dinamarca', 'Janeiro', 2024, 2),
('Aérea', 'Paraná', 'Equador', 'Janeiro', 2024, 3),
('Aérea', 'Paraná', 'Espanha', 'Janeiro', 2024, 23),
('Aérea', 'Paraná', 'Estados Unidos', 'Janeiro', 2024, 43),
('Aérea', 'Paraná', 'França', 'Janeiro', 2024, 8),
('Aérea', 'Paraná', 'Holanda', 'Janeiro', 2024, 7),
('Aérea', 'Paraná', 'Indonésia', 'Janeiro', 2024, 1),
('Aérea', 'Paraná', 'Irlanda', 'Janeiro', 2024, 4),
('Aérea', 'Paraná', 'Israel', 'Janeiro', 2024, 9),
('Aérea', 'Paraná', 'Japão', 'Janeiro', 2024, 7),
('Aérea', 'Paraná', 'Líbano', 'Janeiro', 2024, 1),
('Aérea', 'Paraná', 'Lituânia', 'Janeiro', 2024, 4),
('Aérea', 'Paraná', 'Malásia', 'Janeiro', 2024, 2),
('Aérea', 'Paraná', 'México', 'Janeiro', 2024, 5),
('Aérea', 'Paraná', 'Nova Zelândia', 'Janeiro', 2024, 2),
('Aérea', 'Paraná', 'Panamá', 'Janeiro', 2024, 1),
('Aérea', 'Paraná', 'Paraguai', 'Janeiro', 2024, 73),
('Aérea', 'Paraná', 'Peru', 'Janeiro', 2024, 24),
('Aérea', 'Paraná', 'Polônia', 'Janeiro', 2024, 2),
('Aérea', 'Paraná', 'Reino Unido', 'Janeiro', 2024, 14),
('Aérea', 'Paraná', 'República da Coreia', 'Janeiro', 2024, 13),
('Aérea', 'Paraná', 'Rússia', 'Janeiro', 2024, 3),
('Aérea', 'Paraná', 'Suécia', 'Janeiro', 2024, 5),
('Aérea', 'Paraná', 'Suíça', 'Janeiro', 2024, 4),
('Aérea', 'Paraná', 'Taiwan', 'Janeiro', 2024, 1),
('Aérea', 'Paraná', 'Turquia', 'Janeiro', 2024, 3),
('Aérea', 'Paraná', 'Ucrânia', 'Janeiro', 2024, 1),
('Aérea', 'Paraná', 'Uruguai', 'Janeiro', 2024, 1),
('Aérea', 'Paraná', 'Venezuela', 'Janeiro', 2024, 4),
('Aérea', 'Paraná', 'Alemanha', 'Janeiro', 2024, 7),
('Aérea', 'Paraná', 'Angola', 'Janeiro', 2024, 1),
('Aérea', 'Paraná', 'Argentina', 'Janeiro', 2024, 251),
('Aérea', 'Paraná', 'Austrália', 'Janeiro', 2024, 5),
('Aérea', 'Paraná', 'Áustria', 'Janeiro', 2024, 7),
('Aérea', 'Paraná', 'Bélgica', 'Janeiro', 2024, 2),
('Aérea', 'Paraná', 'Bolívia', 'Janeiro', 2024, 3),
('Aérea', 'Paraná', 'Canadá', 'Janeiro', 2024, 3),
('Aérea', 'Paraná', 'Chile', 'Janeiro', 2024, 177),
('Aérea', 'Paraná', 'China', 'Janeiro', 2024, 3),
('Aérea', 'Paraná', 'Colômbia', 'Janeiro', 2024, 10),
('Aérea', 'Paraná', 'Costa Rica', 'Janeiro', 2024, 2),
('Aérea', 'Paraná', 'Cuba', 'Janeiro', 2024, 2),
('Aérea', 'Paraná', 'Espanha', 'Janeiro', 2024, 4),
('Aérea', 'Paraná', 'Estados Unidos', 'Janeiro', 2024, 21),
('Aérea', 'Paraná', 'Finlândia', 'Janeiro', 2024, 1),
('Aérea', 'Paraná', 'França', 'Janeiro', 2024, 10),
('Aérea', 'Paraná', 'Haiti', 'Janeiro', 2024, 2),
('Aérea', 'Paraná', 'Holanda', 'Janeiro', 2024, 2),
('Aérea', 'Paraná', 'Irlanda', 'Janeiro', 2024, 1),
('Aérea', 'Paraná', 'Itália', 'Janeiro', 2024, 6),
('Aérea', 'Paraná', 'Japão', 'Janeiro', 2024, 3),
('Aérea', 'Paraná', 'México', 'Janeiro', 2024, 6),
('Aérea', 'Paraná', 'Noruega', 'Janeiro', 2024, 3),
('Aérea', 'Paraná', 'Panamá', 'Janeiro', 2024, 2),
('Aérea', 'Paraná', 'Paraguai', 'Janeiro', 2024, 3),
('Aérea', 'Paraná', 'Peru', 'Janeiro', 2024, 4),
('Aérea', 'Paraná', 'Polônia', 'Janeiro', 2024, 1),
('Aérea', 'Paraná', 'Portugal', 'Janeiro', 2024, 9),
('Aérea', 'Paraná', 'Reino Unido', 'Janeiro', 2024, 3),
('Aérea', 'Paraná', 'República Tcheca', 'Janeiro', 2024, 1),
('Aérea', 'Paraná', 'Rússia', 'Janeiro', 2024, 6),
('Aérea', 'Paraná', 'Suécia', 'Janeiro', 2024, 1),
('Aérea', 'Paraná', 'Ucrânia', 'Janeiro', 2024, 1),
('Aérea', 'Paraná', 'Uruguai', 'Janeiro', 2024, 86),
('Aérea', 'Paraná', 'Venezuela', 'Janeiro', 2024, 8),
('Aérea', 'Pernambuco', 'Alemanha', 'Janeiro', 2024, 430),
('Aérea', 'Pernambuco', 'Argentina', 'Janeiro', 2024, 1336),
('Aérea', 'Pernambuco', 'Outros países da Ásia', 'Janeiro', 2024, 1),
('Aérea', 'Pernambuco', 'Austrália', 'Janeiro', 2024, 1),
('Aérea', 'Pernambuco', 'Áustria', 'Janeiro', 2024, 104),
('Aérea', 'Pernambuco', 'Bélgica', 'Janeiro', 2024, 23),
('Aérea', 'Pernambuco', 'Bolívia', 'Janeiro', 2024, 1),
('Aérea', 'Pernambuco', 'Cabo Verde', 'Janeiro', 2024, 1),
('Aérea', 'Pernambuco', 'Canadá', 'Janeiro', 2024, 8),
('Aérea', 'Pernambuco', 'Chile', 'Janeiro', 2024, 2),
('Aérea', 'Pernambuco', 'China', 'Janeiro', 2024, 2),
('Aérea', 'Pernambuco', 'Colômbia', 'Janeiro', 2024, 1),
('Aérea', 'Pernambuco', 'Croácia', 'Janeiro', 2024, 2),
('Aérea', 'Pernambuco', 'Dinamarca', 'Janeiro', 2024, 27),
('Aérea', 'Pernambuco', 'Equador', 'Janeiro', 2024, 2),
('Aérea', 'Pernambuco', 'Eslovênia', 'Janeiro', 2024, 3),
('Aérea', 'Pernambuco', 'Espanha', 'Janeiro', 2024, 190),
('Aérea', 'Pernambuco', 'Estados Unidos', 'Janeiro', 2024, 194),
('Aérea', 'Pernambuco', 'Finlândia', 'Janeiro', 2024, 4),
('Aérea', 'Pernambuco', 'França', 'Janeiro', 2024, 207),
('Aérea', 'Pernambuco', 'Grécia', 'Janeiro', 2024, 2),
('Aérea', 'Pernambuco', 'Holanda', 'Janeiro', 2024, 50),
('Aérea', 'Pernambuco', 'Hungria', 'Janeiro', 2024, 2);

INSERT INTO chegadas_turistas (via_de_acesso, uf, nome_pais_origem, mes, ano, chegadas) VALUES
('Aérea', 'Pernambuco', 'Índia', 'Janeiro', 2024, 1),
('Aérea', 'Pernambuco', 'Irlanda', 'Janeiro', 2024, 28),
('Aérea', 'Pernambuco', 'Israel', 'Janeiro', 2024, 4),
('Aérea', 'Pernambuco', 'Itália', 'Janeiro', 2024, 502),
('Aérea', 'Pernambuco', 'Letônia', 'Janeiro', 2024, 3),
('Aérea', 'Pernambuco', 'Lituânia', 'Janeiro', 2024, 2),
('Aérea', 'Pernambuco', 'Luxemburgo', 'Janeiro', 2024, 4),
('Aérea', 'Pernambuco', 'Malásia', 'Janeiro', 2024, 1),
('Aérea', 'Pernambuco', 'Outros países da Europa', 'Janeiro', 2024, 3),
('Aérea', 'Pernambuco', 'Marrocos', 'Janeiro', 2024, 2),
('Aérea', 'Pernambuco', 'México', 'Janeiro', 2024, 1),
('Aérea', 'Pernambuco', 'Noruega', 'Janeiro', 2024, 25),
('Aérea', 'Pernambuco', 'Peru', 'Janeiro', 2024, 2),
('Aérea', 'Pernambuco', 'Polônia', 'Janeiro', 2024, 16),
('Aérea', 'Pernambuco', 'Portugal', 'Janeiro', 2024, 1057),
('Aérea', 'Pernambuco', 'Reino Unido', 'Janeiro', 2024, 113),
('Aérea', 'Pernambuco', 'República Tcheca', 'Janeiro', 2024, 1),
('Aérea', 'Pernambuco', 'Romênia', 'Janeiro', 2024, 3),
('Aérea', 'Pernambuco', 'Rússia', 'Janeiro', 2024, 3),
('Aérea', 'Pernambuco', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Pernambuco', 'Sérvia', 'Janeiro', 2024, 2),
('Aérea', 'Pernambuco', 'Suécia', 'Janeiro', 2024, 56),
('Aérea', 'Pernambuco', 'Suíça', 'Janeiro', 2024, 137),
('Aérea', 'Pernambuco', 'Ucrânia', 'Janeiro', 2024, 6),
('Aérea', 'Pernambuco', 'Uruguai', 'Janeiro', 2024, 920),
('Aérea', 'Pernambuco', 'Venezuela', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'África do Sul', 'Janeiro', 2024, 156),
('Aérea', 'Rio de Janeiro', 'Outros países da Europa', 'Janeiro', 2024, 12),
('Aérea', 'Rio de Janeiro', 'Alemanha', 'Janeiro', 2024, 2831),
('Aérea', 'Rio de Janeiro', 'Outros países da Europa', 'Janeiro', 2024, 6),
('Aérea', 'Rio de Janeiro', 'Angola', 'Janeiro', 2024, 5),
('Aérea', 'Rio de Janeiro', 'Outros países da América Central e Caribe', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'Arábia Saudita', 'Janeiro', 2024, 14),
('Aérea', 'Rio de Janeiro', 'Outros países da África', 'Janeiro', 2024, 6),
('Aérea', 'Rio de Janeiro', 'Argentina', 'Janeiro', 2024, 54751),
('Aérea', 'Rio de Janeiro', 'Outros países da Ásia', 'Janeiro', 2024, 11),
('Aérea', 'Rio de Janeiro', 'Austrália', 'Janeiro', 2024, 1573),
('Aérea', 'Rio de Janeiro', 'Áustria', 'Janeiro', 2024, 347),
('Aérea', 'Rio de Janeiro', 'Outros países da Europa', 'Janeiro', 2024, 4),
('Aérea', 'Rio de Janeiro', 'Outros países da América Central e Caribe', 'Janeiro', 2024, 9),
('Aérea', 'Rio de Janeiro', 'Outros países da América Central e Caribe', 'Janeiro', 2024, 4),
('Aérea', 'Rio de Janeiro', 'Bélgica', 'Janeiro', 2024, 532),
('Aérea', 'Rio de Janeiro', 'Outros países da América Central e Caribe', 'Janeiro', 2024, 2),
('Aérea', 'Rio de Janeiro', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'Outros países da Europa', 'Janeiro', 2024, 21),
('Aérea', 'Rio de Janeiro', 'Bolívia', 'Janeiro', 2024, 83),
('Aérea', 'Rio de Janeiro', 'Outros países da Europa', 'Janeiro', 2024, 7),
('Aérea', 'Rio de Janeiro', 'Bulgária', 'Janeiro', 2024, 124),
('Aérea', 'Rio de Janeiro', 'Cabo Verde', 'Janeiro', 2024, 3),
('Aérea', 'Rio de Janeiro', 'Outros países da África', 'Janeiro', 2024, 2),
('Aérea', 'Rio de Janeiro', 'Canadá', 'Janeiro', 2024, 1934),
('Aérea', 'Rio de Janeiro', 'Outros países da Ásia', 'Janeiro', 2024, 9),
('Aérea', 'Rio de Janeiro', 'Outros países da Ásia', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'Chile', 'Janeiro', 2024, 36858),
('Aérea', 'Rio de Janeiro', 'China', 'Janeiro', 2024, 352),
('Aérea', 'Rio de Janeiro', 'China, Hong Kong', 'Janeiro', 2024, 22),
('Aérea', 'Rio de Janeiro', 'Outros países da Ásia', 'Janeiro', 2024, 2),
('Aérea', 'Rio de Janeiro', 'Outros países da Ásia', 'Janeiro', 2024, 15),
('Aérea', 'Rio de Janeiro', 'Cingapura', 'Janeiro', 2024, 46),
('Aérea', 'Rio de Janeiro', 'Colômbia', 'Janeiro', 2024, 1853),
('Aérea', 'Rio de Janeiro', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'Costa Rica', 'Janeiro', 2024, 350),
('Aérea', 'Rio de Janeiro', 'Croácia', 'Janeiro', 2024, 51),
('Aérea', 'Rio de Janeiro', 'Cuba', 'Janeiro', 2024, 26),
('Aérea', 'Rio de Janeiro', 'Dinamarca', 'Janeiro', 2024, 506),
('Aérea', 'Rio de Janeiro', 'Outros países da América Central e Caribe', 'Janeiro', 2024, 12),
('Aérea', 'Rio de Janeiro', 'Egito', 'Janeiro', 2024, 10),
('Aérea', 'Rio de Janeiro', 'El Salvador', 'Janeiro', 2024, 24),
('Aérea', 'Rio de Janeiro', 'Outros países da Ásia', 'Janeiro', 2024, 9),
('Aérea', 'Rio de Janeiro', 'Equador', 'Janeiro', 2024, 285),
('Aérea', 'Rio de Janeiro', 'Eslováquia', 'Janeiro', 2024, 79),
('Aérea', 'Rio de Janeiro', 'Eslovênia', 'Janeiro', 2024, 53),
('Aérea', 'Rio de Janeiro', 'Espanha', 'Janeiro', 2024, 1370),
('Aérea', 'Rio de Janeiro', 'Estados Unidos', 'Janeiro', 2024, 14166),
('Aérea', 'Rio de Janeiro', 'Estônia', 'Janeiro', 2024, 28),
('Aérea', 'Rio de Janeiro', 'Outros países da África', 'Janeiro', 2024, 3),
('Aérea', 'Rio de Janeiro', 'Outros países da Oceania', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'Filipinas', 'Janeiro', 2024, 62),
('Aérea', 'Rio de Janeiro', 'Finlândia', 'Janeiro', 2024, 135),
('Aérea', 'Rio de Janeiro', 'França', 'Janeiro', 2024, 5000),
('Aérea', 'Rio de Janeiro', 'Gana', 'Janeiro', 2024, 3),
('Aérea', 'Rio de Janeiro', 'Outros países da Europa', 'Janeiro', 2024, 22),
('Aérea', 'Rio de Janeiro', 'Outros países da América Central e Caribe', 'Janeiro', 2024, 3),
('Aérea', 'Rio de Janeiro', 'Grécia', 'Janeiro', 2024, 144),
('Aérea', 'Rio de Janeiro', 'Guatemala', 'Janeiro', 2024, 58),
('Aérea', 'Rio de Janeiro', 'Guiana', 'Janeiro', 2024, 6),
('Aérea', 'Rio de Janeiro', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'Outros países da África', 'Janeiro', 2024, 4),
('Aérea', 'Rio de Janeiro', 'Haiti', 'Janeiro', 2024, 6),
('Aérea', 'Rio de Janeiro', 'Holanda', 'Janeiro', 2024, 1296),
('Aérea', 'Rio de Janeiro', 'Honduras', 'Janeiro', 2024, 47),
('Aérea', 'Rio de Janeiro', 'Hungria', 'Janeiro', 2024, 282),
('Aérea', 'Rio de Janeiro', 'Outros países da Oceania', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'Índia', 'Janeiro', 2024, 95),
('Aérea', 'Rio de Janeiro', 'Indonésia', 'Janeiro', 2024, 16),
('Aérea', 'Rio de Janeiro', 'Irã', 'Janeiro', 2024, 9),
('Aérea', 'Rio de Janeiro', 'Outros países da Ásia', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'Irlanda', 'Janeiro', 2024, 1170),
('Aérea', 'Rio de Janeiro', 'Outros países da Europa', 'Janeiro', 2024, 17),
('Aérea', 'Rio de Janeiro', 'Israel', 'Janeiro', 2024, 228),
('Aérea', 'Rio de Janeiro', 'Itália', 'Janeiro', 2024, 2309),
('Aérea', 'Rio de Janeiro', 'Outros países da América Central e Caribe', 'Janeiro', 2024, 20),
('Aérea', 'Rio de Janeiro', 'Japão', 'Janeiro', 2024, 185),
('Aérea', 'Rio de Janeiro', 'Outros países da Ásia', 'Janeiro', 2024, 5),
('Aérea', 'Rio de Janeiro', 'Outros países da Ásia', 'Janeiro', 2024, 5),
('Aérea', 'Rio de Janeiro', 'Letônia', 'Janeiro', 2024, 16),
('Aérea', 'Rio de Janeiro', 'Líbano', 'Janeiro', 2024, 13),
('Aérea', 'Rio de Janeiro', 'Outros países da Europa', 'Janeiro', 2024, 5),
('Aérea', 'Rio de Janeiro', 'Lituânia', 'Janeiro', 2024, 47),
('Aérea', 'Rio de Janeiro', 'Luxemburgo', 'Janeiro', 2024, 48),
('Aérea', 'Rio de Janeiro', 'Outros países da Europa', 'Janeiro', 2024, 8),
('Aérea', 'Rio de Janeiro', 'Malásia', 'Janeiro', 2024, 61),
('Aérea', 'Rio de Janeiro', 'Outros países da Europa', 'Janeiro', 2024, 18),
('Aérea', 'Rio de Janeiro', 'Marrocos', 'Janeiro', 2024, 28),
('Aérea', 'Rio de Janeiro', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'México', 'Janeiro', 2024, 791),
('Aérea', 'Rio de Janeiro', 'Outros países da Ásia', 'Janeiro', 2024, 2),
('Aérea', 'Rio de Janeiro', 'Moçambique', 'Janeiro', 2024, 4),
('Aérea', 'Rio de Janeiro', 'Outros países da Europa', 'Janeiro', 2024, 2),
('Aérea', 'Rio de Janeiro', 'Outros países da Europa', 'Janeiro', 2024, 8),
('Aérea', 'Rio de Janeiro', 'Outros países da Ásia', 'Janeiro', 2024, 2),
('Aérea', 'Rio de Janeiro', 'Outros países da Europa', 'Janeiro', 2024, 5),
('Aérea', 'Rio de Janeiro', 'Outros países da África', 'Janeiro', 2024, 2),
('Aérea', 'Rio de Janeiro', 'Outros países da Ásia', 'Janeiro', 2024, 3),
('Aérea', 'Rio de Janeiro', 'Nicarágua', 'Janeiro', 2024, 18),
('Aérea', 'Rio de Janeiro', 'Nigéria', 'Janeiro', 2024, 4),
('Aérea', 'Rio de Janeiro', 'Noruega', 'Janeiro', 2024, 472),
('Aérea', 'Rio de Janeiro', 'Nova Zelândia', 'Janeiro', 2024, 88),
('Aérea', 'Rio de Janeiro', 'Outros países da Ásia', 'Janeiro', 2024, 2),
('Aérea', 'Rio de Janeiro', 'Panamá', 'Janeiro', 2024, 239),
('Aérea', 'Rio de Janeiro', 'Paquistão', 'Janeiro', 2024, 10),
('Aérea', 'Rio de Janeiro', 'Paraguai', 'Janeiro', 2024, 596),
('Aérea', 'Rio de Janeiro', 'Peru', 'Janeiro', 2024, 1463),
('Aérea', 'Rio de Janeiro', 'Polônia', 'Janeiro', 2024, 988),
('Aérea', 'Rio de Janeiro', 'Outros países da América Central e Caribe', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'Portugal', 'Janeiro', 2024, 3312),
('Aérea', 'Rio de Janeiro', 'Quênia', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'Reino Unido', 'Janeiro', 2024, 3586),
('Aérea', 'Rio de Janeiro', 'República da Coreia', 'Janeiro', 2024, 256),
('Aérea', 'Rio de Janeiro', 'Outros países da Europa', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'República Dominicana', 'Janeiro', 2024, 51),
('Aérea', 'Rio de Janeiro', 'República Tcheca', 'Janeiro', 2024, 312),
('Aérea', 'Rio de Janeiro', 'Romênia', 'Janeiro', 2024, 157),
('Aérea', 'Rio de Janeiro', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'Rússia', 'Janeiro', 2024, 505),
('Aérea', 'Rio de Janeiro', 'Outros países da Europa', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'Outros países da América Central e Caribe', 'Janeiro', 2024, 2),
('Aérea', 'Rio de Janeiro', 'Outros países da América Central e Caribe', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'Outros países da África', 'Janeiro', 2024, 2),
('Aérea', 'Rio de Janeiro', 'Outros países da África', 'Janeiro', 2024, 8),
('Aérea', 'Rio de Janeiro', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'Sérvia', 'Janeiro', 2024, 66),
('Aérea', 'Rio de Janeiro', 'Outros países da Ásia', 'Janeiro', 2024, 2),
('Aérea', 'Rio de Janeiro', 'Suécia', 'Janeiro', 2024, 752),
('Aérea', 'Rio de Janeiro', 'Suíça', 'Janeiro', 2024, 757),
('Aérea', 'Rio de Janeiro', 'Tailândia', 'Janeiro', 2024, 13),
('Aérea', 'Rio de Janeiro', 'Taiwan', 'Janeiro', 2024, 44),
('Aérea', 'Rio de Janeiro', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'Trinidad e Tobago', 'Janeiro', 2024, 11),
('Aérea', 'Rio de Janeiro', 'Tunísia', 'Janeiro', 2024, 28),
('Aérea', 'Rio de Janeiro', 'Turquia', 'Janeiro', 2024, 124),
('Aérea', 'Rio de Janeiro', 'Ucrânia', 'Janeiro', 2024, 129),
('Aérea', 'Rio de Janeiro', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'Uruguai', 'Janeiro', 2024, 4613),
('Aérea', 'Rio de Janeiro', 'Outros países da Europa', 'Janeiro', 2024, 1),
('Aérea', 'Rio de Janeiro', 'Venezuela', 'Janeiro', 2024, 218),
('Aérea', 'Rio de Janeiro', 'Outros países da Ásia', 'Janeiro', 2024, 6),
('Aérea', 'Rio de Janeiro', 'Outros países da África', 'Janeiro', 2024, 3),
('Aérea', 'Rio Grande do Norte', 'Outros países da Europa', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Norte', 'Alemanha', 'Janeiro', 2024, 110),
('Aérea', 'Rio Grande do Norte', 'Argentina', 'Janeiro', 2024, 1318),
('Aérea', 'Rio Grande do Norte', 'Áustria', 'Janeiro', 2024, 12),
('Aérea', 'Rio Grande do Norte', 'Bélgica', 'Janeiro', 2024, 16),
('Aérea', 'Rio Grande do Norte', 'Bulgária', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Norte', 'Chile', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Norte', 'China', 'Janeiro', 2024, 2),
('Aérea', 'Rio Grande do Norte', 'Colômbia', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Norte', 'Dinamarca', 'Janeiro', 2024, 10),
('Aérea', 'Rio Grande do Norte', 'Espanha', 'Janeiro', 2024, 129),
('Aérea', 'Rio Grande do Norte', 'Estados Unidos', 'Janeiro', 2024, 3),
('Aérea', 'Rio Grande do Norte', 'Estônia', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Norte', 'Finlândia', 'Janeiro', 2024, 5),
('Aérea', 'Rio Grande do Norte', 'França', 'Janeiro', 2024, 133),
('Aérea', 'Rio Grande do Norte', 'Holanda', 'Janeiro', 2024, 61),
('Aérea', 'Rio Grande do Norte', 'Hungria', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Norte', 'Irlanda', 'Janeiro', 2024, 11),
('Aérea', 'Rio Grande do Norte', 'Itália', 'Janeiro', 2024, 361),
('Aérea', 'Rio Grande do Norte', 'Lituânia', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Norte', 'Luxemburgo', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Norte', 'Noruega', 'Janeiro', 2024, 127),
('Aérea', 'Rio Grande do Norte', 'Paraguai', 'Janeiro', 2024, 4),
('Aérea', 'Rio Grande do Norte', 'Polônia', 'Janeiro', 2024, 8),
('Aérea', 'Rio Grande do Norte', 'Portugal', 'Janeiro', 2024, 542),
('Aérea', 'Rio Grande do Norte', 'Reino Unido', 'Janeiro', 2024, 32),
('Aérea', 'Rio Grande do Norte', 'República Tcheca', 'Janeiro', 2024, 3),
('Aérea', 'Rio Grande do Norte', 'Romênia', 'Janeiro', 2024, 6),
('Aérea', 'Rio Grande do Norte', 'Rússia', 'Janeiro', 2024, 5),
('Aérea', 'Rio Grande do Norte', 'Sérvia', 'Janeiro', 2024, 4),
('Aérea', 'Rio Grande do Norte', 'Suécia', 'Janeiro', 2024, 47),
('Aérea', 'Rio Grande do Norte', 'Suíça', 'Janeiro', 2024, 77),
('Aérea', 'Rio Grande do Norte', 'Tunísia', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Norte', 'Ucrânia', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Norte', 'Uruguai', 'Janeiro', 2024, 5),
('Aérea', 'Rio Grande do Norte', 'Venezuela', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'Portugal', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'África do Sul', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'Alemanha', 'Janeiro', 2024, 232),
('Aérea', 'Rio Grande do Sul', 'Argentina', 'Janeiro', 2024, 341),
('Aérea', 'Rio Grande do Sul', 'Austrália', 'Janeiro', 2024, 13),
('Aérea', 'Rio Grande do Sul', 'Bélgica', 'Janeiro', 2024, 11),
('Aérea', 'Rio Grande do Sul', 'Bolívia', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'Outros países da Europa', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'Cabo Verde', 'Janeiro', 2024, 2),
('Aérea', 'Rio Grande do Sul', 'Canadá', 'Janeiro', 2024, 18),
('Aérea', 'Rio Grande do Sul', 'Chile', 'Janeiro', 2024, 367),
('Aérea', 'Rio Grande do Sul', 'China', 'Janeiro', 2024, 14),
('Aérea', 'Rio Grande do Sul', 'China, Hong Kong', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'Colômbia', 'Janeiro', 2024, 90),
('Aérea', 'Rio Grande do Sul', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'Costa Rica', 'Janeiro', 2024, 6),
('Aérea', 'Rio Grande do Sul', 'Croácia', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'Cuba', 'Janeiro', 2024, 4),
('Aérea', 'Rio Grande do Sul', 'Dinamarca', 'Janeiro', 2024, 3),
('Aérea', 'Rio Grande do Sul', 'El Salvador', 'Janeiro', 2024, 2),
('Aérea', 'Rio Grande do Sul', 'Equador', 'Janeiro', 2024, 91),
('Aérea', 'Rio Grande do Sul', 'Eslovênia', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'Espanha', 'Janeiro', 2024, 42),
('Aérea', 'Rio Grande do Sul', 'Estados Unidos', 'Janeiro', 2024, 523),
('Aérea', 'Rio Grande do Sul', 'Filipinas', 'Janeiro', 2024, 2),
('Aérea', 'Rio Grande do Sul', 'Finlândia', 'Janeiro', 2024, 4),
('Aérea', 'Rio Grande do Sul', 'França', 'Janeiro', 2024, 27),
('Aérea', 'Rio Grande do Sul', 'Grécia', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'Guatemala', 'Janeiro', 2024, 5),
('Aérea', 'Rio Grande do Sul', 'Haiti', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'Holanda', 'Janeiro', 2024, 18),
('Aérea', 'Rio Grande do Sul', 'Honduras', 'Janeiro', 2024, 11),
('Aérea', 'Rio Grande do Sul', 'Índia', 'Janeiro', 2024, 3),
('Aérea', 'Rio Grande do Sul', 'Irlanda', 'Janeiro', 2024, 12),
('Aérea', 'Rio Grande do Sul', 'Israel', 'Janeiro', 2024, 2),
('Aérea', 'Rio Grande do Sul', 'Itália', 'Janeiro', 2024, 78),
('Aérea', 'Rio Grande do Sul', 'Japão', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'Outros países da Ásia', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'Letônia', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'Lituânia', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'Luxemburgo', 'Janeiro', 2024, 4),
('Aérea', 'Rio Grande do Sul', 'Marrocos', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'Outros países da África', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'México', 'Janeiro', 2024, 14),
('Aérea', 'Rio Grande do Sul', 'Noruega', 'Janeiro', 2024, 3),
('Aérea', 'Rio Grande do Sul', 'Nova Zelândia', 'Janeiro', 2024, 14),
('Aérea', 'Rio Grande do Sul', 'Panamá', 'Janeiro', 2024, 17),
('Aérea', 'Rio Grande do Sul', 'Paraguai', 'Janeiro', 2024, 4),
('Aérea', 'Rio Grande do Sul', 'Peru', 'Janeiro', 2024, 163),
('Aérea', 'Rio Grande do Sul', 'Polônia', 'Janeiro', 2024, 5),
('Aérea', 'Rio Grande do Sul', 'Portugal', 'Janeiro', 2024, 172),
('Aérea', 'Rio Grande do Sul', 'Reino Unido', 'Janeiro', 2024, 170),
('Aérea', 'Rio Grande do Sul', 'República Dominicana', 'Janeiro', 2024, 7),
('Aérea', 'Rio Grande do Sul', 'República Tcheca', 'Janeiro', 2024, 3),
('Aérea', 'Rio Grande do Sul', 'Romênia', 'Janeiro', 2024, 4),
('Aérea', 'Rio Grande do Sul', 'Rússia', 'Janeiro', 2024, 12),
('Aérea', 'Rio Grande do Sul', 'Sérvia', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'Outros países da Ásia', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'Suécia', 'Janeiro', 2024, 11),
('Aérea', 'Rio Grande do Sul', 'Suíça', 'Janeiro', 2024, 13),
('Aérea', 'Rio Grande do Sul', 'Ucrânia', 'Janeiro', 2024, 1),
('Aérea', 'Rio Grande do Sul', 'Uruguai', 'Janeiro', 2024, 350),
('Aérea', 'Rio Grande do Sul', 'Venezuela', 'Janeiro', 2024, 4),
('Aérea', 'Rio Grande do Sul', 'Outros países da Ásia', 'Janeiro', 2024, 1),
('Aérea', 'Roraima', 'Suriname', 'Janeiro', 2024, 4),
('Aérea', 'Roraima', 'Uruguai', 'Janeiro', 2024, 1),
('Aérea', 'Santa Catarina', 'África do Sul', 'Janeiro', 2024, 11),
('Aérea', 'Santa Catarina', 'Alemanha', 'Janeiro', 2024, 224),
('Aérea', 'Santa Catarina', 'Outros países da Europa', 'Janeiro', 2024, 1),
('Aérea', 'Santa Catarina', 'Argentina', 'Janeiro', 2024, 36030),
('Aérea', 'Santa Catarina', 'Austrália', 'Janeiro', 2024, 33),
('Aérea', 'Santa Catarina', 'Áustria', 'Janeiro', 2024, 11),
('Aérea', 'Santa Catarina', 'Bélgica', 'Janeiro', 2024, 9),
('Aérea', 'Santa Catarina', 'Bolívia', 'Janeiro', 2024, 44),
('Aérea', 'Santa Catarina', 'Bulgária', 'Janeiro', 2024, 5),
('Aérea', 'Santa Catarina', 'Canadá', 'Janeiro', 2024, 36),
('Aérea', 'Santa Catarina', 'Outros países da Ásia', 'Janeiro', 2024, 2),
('Aérea', 'Santa Catarina', 'Chile', 'Janeiro', 2024, 20357),
('Aérea', 'Santa Catarina', 'China', 'Janeiro', 2024, 4),
('Aérea', 'Santa Catarina', 'Cingapura', 'Janeiro', 2024, 1),
('Aérea', 'Santa Catarina', 'Colômbia', 'Janeiro', 2024, 141),
('Aérea', 'Santa Catarina', 'Costa Rica', 'Janeiro', 2024, 7),
('Aérea', 'Santa Catarina', 'Croácia', 'Janeiro', 2024, 3),
('Aérea', 'Santa Catarina', 'Cuba', 'Janeiro', 2024, 33),
('Aérea', 'Santa Catarina', 'Dinamarca', 'Janeiro', 2024, 3),
('Aérea', 'Santa Catarina', 'El Salvador', 'Janeiro', 2024, 6),
('Aérea', 'Santa Catarina', 'Equador', 'Janeiro', 2024, 38),
('Aérea', 'Santa Catarina', 'Eslováquia', 'Janeiro', 2024, 1),
('Aérea', 'Santa Catarina', 'Eslovênia', 'Janeiro', 2024, 2),
('Aérea', 'Santa Catarina', 'Espanha', 'Janeiro', 2024, 109),
('Aérea', 'Santa Catarina', 'Estados Unidos', 'Janeiro', 2024, 278),
('Aérea', 'Santa Catarina', 'Finlândia', 'Janeiro', 2024, 4),
('Aérea', 'Santa Catarina', 'França', 'Janeiro', 2024, 57),
('Aérea', 'Santa Catarina', 'Grécia', 'Janeiro', 2024, 6),
('Aérea', 'Santa Catarina', 'Guatemala', 'Janeiro', 2024, 2),
('Aérea', 'Santa Catarina', 'Guiana', 'Janeiro', 2024, 3),
('Aérea', 'Santa Catarina', 'Haiti', 'Janeiro', 2024, 2),
('Aérea', 'Santa Catarina', 'Holanda', 'Janeiro', 2024, 29),
('Aérea', 'Santa Catarina', 'Honduras', 'Janeiro', 2024, 2),
('Aérea', 'Santa Catarina', 'Hungria', 'Janeiro', 2024, 2),
('Aérea', 'Santa Catarina', 'Índia', 'Janeiro', 2024, 4),
('Aérea', 'Santa Catarina', 'Irlanda', 'Janeiro', 2024, 10),
('Aérea', 'Santa Catarina', 'Israel', 'Janeiro', 2024, 16),
('Aérea', 'Santa Catarina', 'Itália', 'Janeiro', 2024, 111),
('Aérea', 'Santa Catarina', 'Japão', 'Janeiro', 2024, 5),
('Aérea', 'Santa Catarina', 'Lituânia', 'Janeiro', 2024, 6),
('Aérea', 'Santa Catarina', 'Luxemburgo', 'Janeiro', 2024, 1),
('Aérea', 'Santa Catarina', 'México', 'Janeiro', 2024, 27),
('Aérea', 'Santa Catarina', 'Outros países da Ásia', 'Janeiro', 2024, 1),
('Aérea', 'Santa Catarina', 'Nicarágua', 'Janeiro', 2024, 2),
('Aérea', 'Santa Catarina', 'Noruega', 'Janeiro', 2024, 6),
('Aérea', 'Santa Catarina', 'Nova Zelândia', 'Janeiro', 2024, 2),
('Aérea', 'Santa Catarina', 'Panamá', 'Janeiro', 2024, 3),
('Aérea', 'Santa Catarina', 'Paraguai', 'Janeiro', 2024, 516),
('Aérea', 'Santa Catarina', 'Peru', 'Janeiro', 2024, 277),
('Aérea', 'Santa Catarina', 'Polônia', 'Janeiro', 2024, 14),
('Aérea', 'Santa Catarina', 'Portugal', 'Janeiro', 2024, 43),
('Aérea', 'Santa Catarina', 'Reino Unido', 'Janeiro', 2024, 63),
('Aérea', 'Santa Catarina', 'República da Coreia', 'Janeiro', 2024, 3),
('Aérea', 'Santa Catarina', 'República Dominicana', 'Janeiro', 2024, 2),
('Aérea', 'Santa Catarina', 'República Tcheca', 'Janeiro', 2024, 2),
('Aérea', 'Santa Catarina', 'Romênia', 'Janeiro', 2024, 2),
('Aérea', 'Santa Catarina', 'Rússia', 'Janeiro', 2024, 72),
('Aérea', 'Santa Catarina', 'Suécia', 'Janeiro', 2024, 24),
('Aérea', 'Santa Catarina', 'Suíça', 'Janeiro', 2024, 41),
('Aérea', 'Santa Catarina', 'Taiwan', 'Janeiro', 2024, 1),
('Aérea', 'Santa Catarina', 'Turquia', 'Janeiro', 2024, 5),
('Aérea', 'Santa Catarina', 'Ucrânia', 'Janeiro', 2024, 11),
('Aérea', 'Santa Catarina', 'Uruguai', 'Janeiro', 2024, 2379),
('Aérea', 'Santa Catarina', 'Venezuela', 'Janeiro', 2024, 70),
('Aérea', 'Santa Catarina', 'Outros países da América Central e Caribe', 'Janeiro', 2024, 1),
('Aérea', 'Santa Catarina', 'Argentina', 'Janeiro', 2024, 1500),
('Aérea', 'Santa Catarina', 'Áustria', 'Janeiro', 2024, 2),
('Aérea', 'Santa Catarina', 'Bélgica', 'Janeiro', 2024, 1),
('Aérea', 'Santa Catarina', 'Bolívia', 'Janeiro', 2024, 1),
('Aérea', 'Santa Catarina', 'Canadá', 'Janeiro', 2024, 1),
('Aérea', 'Santa Catarina', 'Chile', 'Janeiro', 2024, 3),
('Aérea', 'Santa Catarina', 'Colômbia', 'Janeiro', 2024, 6),
('Aérea', 'Santa Catarina', 'Costa Rica', 'Janeiro', 2024, 2),
('Aérea', 'Santa Catarina', 'Equador', 'Janeiro', 2024, 1),
('Aérea', 'Santa Catarina', 'Espanha', 'Janeiro', 2024, 4),
('Aérea', 'Santa Catarina', 'Estados Unidos', 'Janeiro', 2024, 2),
('Aérea', 'Santa Catarina', 'Itália', 'Janeiro', 2024, 2),
('Aérea', 'Santa Catarina', 'Paraguai', 'Janeiro', 2024, 5),
('Aérea', 'Santa Catarina', 'Portugal', 'Janeiro', 2024, 2),
('Aérea', 'Santa Catarina', 'Reino Unido', 'Janeiro', 2024, 1),
('Aérea', 'Santa Catarina', 'Uruguai', 'Janeiro', 2024, 5),
('Aérea', 'Santa Catarina', 'Venezuela', 'Janeiro', 2024, 4),
('Aérea', 'São Paulo', 'Alemanha', 'Janeiro', 2024, 104);
 
CREATE TABLE filtro_personalizado (
    id_filtro        INT AUTO_INCREMENT PRIMARY KEY,
    nome             VARCHAR(100) NOT NULL,
    descricao        VARCHAR(255),
    ano_referencia   INT,
    mes_inicio       VARCHAR(20),
    mes_fim          VARCHAR(20),
    fk_usuario       INT NOT NULL,
    data_criacao     DATETIME DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (fk_usuario) REFERENCES usuario(id_usuario)
);
 
 
CREATE TABLE filtro_item (
    id_filtro_item INT AUTO_INCREMENT PRIMARY KEY,
    fk_filtro      INT          NOT NULL,
    tipo           VARCHAR(6)   NOT NULL,
    valor          VARCHAR(100) NOT NULL,
    CONSTRAINT chk_tipo CHECK (tipo IN ('PAIS', 'ESTADO')),
    FOREIGN KEY (fk_filtro) REFERENCES filtro_personalizado(id_filtro) ON DELETE CASCADE
);
 
 
CREATE VIEW vw_solicitacoes AS
SELECT
    sc.id_solicitacao,
    sc.nome_responsavel,
    sc.email_responsavel,
    sc.telefone_responsavel,
    sc.nome_empresa,
    sc.cnpj_empresa,
    sc.email_empresa,
    sc.telefone_empresa,
    sc.data_criacao,
    s.nome AS status
FROM solicitacao_cadastro sc
INNER JOIN status s ON s.id_status = sc.fk_status;
 
 
CREATE VIEW vw_empresas AS
SELECT
    e.id_empresa,
    e.nome,
    e.cnpj,
    e.email,
    e.telefone,
    s.nome AS status,
    e.data_criacao,
    COUNT(u.id_usuario) AS total_usuarios
FROM empresa e
INNER JOIN status s  ON s.id_status  = e.fk_status
LEFT  JOIN usuario u ON u.fk_empresa = e.id_empresa
GROUP BY e.id_empresa, e.nome, e.cnpj, e.email, e.telefone, s.nome, e.data_criacao;
 
 
CREATE VIEW vw_usuarios AS
SELECT
    u.id_usuario,
    u.nome,
    u.email,
    u.primeiro_acesso,
    u.data_criacao,
    np.nome AS nivel_permissao,
    s.nome  AS status,
    e.id_empresa,
    e.nome  AS empresa
FROM usuario u
INNER JOIN nivel_permissao np ON np.id_nivel_permissao = u.fk_nivel_permissao
INNER JOIN status s           ON s.id_status           = u.fk_status
LEFT  JOIN empresa e          ON e.id_empresa          = u.fk_empresa;
 
 
CREATE VIEW vw_metricas_filtro AS
SELECT
    ct.ano,
    COUNT(DISTINCT ct.uf) AS total_estados,
    SUM(ct.chegadas)      AS total_turistas,
    (
        SELECT nome_pais_origem
        FROM chegadas_turistas ct2
        WHERE ct2.ano = ct.ano
        GROUP BY nome_pais_origem
        ORDER BY SUM(chegadas) DESC
        LIMIT 1
    ) AS pais_lider,
    ROUND(
        (
            SELECT SUM(chegadas)
            FROM chegadas_turistas ct2
            WHERE ct2.ano = ct.ano
              AND ct2.nome_pais_origem = (
                  SELECT nome_pais_origem
                  FROM chegadas_turistas ct3
                  WHERE ct3.ano = ct.ano
                  GROUP BY nome_pais_origem
                  ORDER BY SUM(chegadas) DESC
                  LIMIT 1
              )
        ) * 100.0 / SUM(ct.chegadas), 0
    ) AS percentual_pais_lider,
    (
        SELECT mes
        FROM chegadas_turistas ct2
        WHERE ct2.ano = ct.ano
        GROUP BY mes
        ORDER BY SUM(chegadas) DESC
        LIMIT 1
    ) AS melhor_mes,
    (
        SELECT SUM(chegadas)
        FROM chegadas_turistas ct2
        WHERE ct2.ano = ct.ano
          AND ct2.mes = (
              SELECT mes
              FROM chegadas_turistas ct3
              WHERE ct3.ano = ct.ano
              GROUP BY mes
              ORDER BY SUM(chegadas) DESC
              LIMIT 1
          )
    ) AS turistas_melhor_mes
FROM chegadas_turistas ct
GROUP BY ct.ano;
 
 
CREATE VIEW vw_fluxo_mensal AS
SELECT
    ano,
    mes,
    SUM(chegadas) AS total_turistas,
    CASE mes
        WHEN 'Janeiro'   THEN 1
        WHEN 'Fevereiro' THEN 2
        WHEN 'Marco'     THEN 3
        WHEN 'Abril'     THEN 4
        WHEN 'Maio'      THEN 5
        WHEN 'Junho'     THEN 6
        WHEN 'Julho'     THEN 7
        WHEN 'Agosto'    THEN 8
        WHEN 'Setembro'  THEN 9
        WHEN 'Outubro'   THEN 10
        WHEN 'Novembro'  THEN 11
        WHEN 'Dezembro'  THEN 12
    END AS mes_numero
FROM chegadas_turistas
GROUP BY ano, mes
ORDER BY ano, mes_numero;
 
 
CREATE VIEW vw_ranking_paises AS
SELECT
    ano,
    nome_pais_origem,
    SUM(chegadas) AS total_turistas,
    ROUND(
        SUM(chegadas) * 100.0 / (
            SELECT SUM(chegadas)
            FROM chegadas_turistas ct2
            WHERE ct2.ano = ct.ano
        ), 0
    ) AS percentual
FROM chegadas_turistas ct
GROUP BY ano, nome_pais_origem
ORDER BY ano, total_turistas DESC;
 
 
CREATE VIEW vw_dashboard_filtrado AS
SELECT
    ct.ano,
    ct.mes,
    ct.uf,
    ct.nome_pais_origem,
    ct.via_de_acesso,
    SUM(ct.chegadas) AS total_turistas
FROM chegadas_turistas ct
GROUP BY ct.ano, ct.mes, ct.uf, ct.nome_pais_origem, ct.via_de_acesso;
 
 
SELECT * FROM vw_empresas ORDER BY nome ASC;
 
SELECT * FROM vw_empresas WHERE nome LIKE '%empresa teste%' ORDER BY nome ASC;
 
SELECT * FROM vw_usuarios WHERE status != 'PENDENTE' ORDER BY nome ASC;
 
SELECT * FROM vw_usuarios
WHERE status     != 'PENDENTE'
  AND id_empresa  = 1
  AND nome LIKE '%joao%'
ORDER BY nome ASC;
 
SELECT * FROM vw_solicitacoes ORDER BY data_criacao DESC;
 
SELECT * FROM vw_solicitacoes WHERE id_solicitacao = 1;
 
SELECT id_log, tabela, registros_lidos, sucesso, mensagem, data_criacao
FROM log
ORDER BY data_criacao DESC;